#!/usr/bin/python


frag_msgs = {
        "mk23_head":" (.+) has a hole in .+ head from (.+)'s Mark 23 pistol",
        "mk23_chest":" (.+) loses a vital chest organ thanks to (.+)'s",
        "mk23_stom":" (.+) loses .+ lunch to (.+)'s",
        "mk23_leg":" (.+) is legless because of (.+)'s",
	"mk23_kill":"(.+) was shot by (.+)'s Mark 23 Pistol",
        "mp5_head":" (.+)'s brains are on the wall thanks to (.+)'s 10mm MP5/10 round",
        "mp5_chest":" (.+) feels some chest pain via (.+)'s MP5/10 Submachinegun",
        "mp5_stom":" (.+) needs some Pepto Bismol after (.+)'s 10mm MP5 round",
        "mp5_leg":" (.+) had .+ legs blown off thanks to (.+)'s MP5/10 Submachinegun",
	"mp5_kill":"(.+) was shot by (.+)'s MP5/10 Submachinegun",
        "m4_head":" (.+) had a makeover by (.+)'s M4 Assault Rifle",
        "m4_chest":" (.+) feels some heart burn thanks to (.+)'s M4 Assault Rifle",
        "m4_stom":" (.+) has an upset stomach thanks to (.+)'s M4 Assault Rifle",
        "m4_leg":" (.+) is now shorter thanks to (.+)'s M4 Assault Rifle",
	"m4_kill":"(.+) was shot by (.+)'s M4 Assault Rifle",
        "m3_kill1":" (.+) accepts (.+)'s M3 Super 90 Assault Shotgun in hole-y matrimony",
	"m3_kill2":" (.+) is full of buckshot from (.+)'s M3 Super 90 Assault Shotgun",
        "hc_kill1":" (.+) underestimated (.+)'s",
        "hc_kill2":" (.+) won't be able to pass a metal detector anymore thanks to (.+)'s",
        "hc_kill3":" (.+) ate (.+)'s sawed-off shotgun",
        "hc_kill4":" (.+) is full of buckshot from (.+)'s sawed off shotgun",
        "ssg_head_zoom":" (.+) saw the sniper bullet go through .+ scope thanks to (.+)",
        "ssg_head":" (.+) caught a sniper bullet between the eyes from (.+)",
        "ssg_chest":" (.+) was picked off by (.+)",
        "ssg_stom":" (.+) was sniped in the stomach by (.+)",
        "ssg_leg":" (.+) was shot in the legs by (.+)",
        "ssg_kill":" (.+) was sniped by (.+)",
        "akimbo_head":" (.+) was trepanned by (.+)'s akimbo Mark 23 pistols",
        "akimbo_chest":" (.+) was John Woo'd by (.+)'s",
        "akimbo_stom":" (.+) needs some new kidneys thanks to (.+)'s",
        "akimbo_leg":" (.+) was shot in the legs by (.+)'s",
	"akimbo_kill":" (.+) was shot by (.+)'s pair of Mark 23 Pistols",
        "sknife_head":" (.+) had .+ throat slit by (.+)'s",
        "sknife_chest":" (.+) had open heart surgery, compliments of (.+)'s",
        "sknife_stom":" (.+) was gutted by (.+)'s",
        "sknife_leg":" (.+) was stabbed repeatedly in the legs by (.+)'s",
        "sknife_kill":" (.+) was slashed apart by (.+)'s",
        "tknife_head":" (.+) caught (.+)'s flying knife with .+ forehead",
        "tknife_chest":" (.+)'s ribs don't help against (.+)'s flying knife",
        "tknife_stom":" (.+) sees the contents of .+ own stomach thanks to (.+)'s",
        "tknife_leg":" (.+) had .+ leg cut off thanks to (.+)",
	"tknife_kill":"(.+) was hit by (.+)'s flying Combat Knife",
        "gas_kill":" (.+) sucks down some toxic gas thanks to (.+)'s",
        "kick_kill1":" (.+) got .+ ass kicked by (.+)",
        "kick_kill2":" (.+) couldn't remove (.+)'s boot from .+ ass",
        "kick_kill3":" (.+) had a Bruce Lee put on .+ by (.+), with a quickness",
        "punch_kill1":" (.+) got a free facelift by (.+)",
        "punch_kill2":" (.+) was knocked out by (.+)",
        "punch_kill3":" (.+) iron fist (.+)",
        "glass_kill":" (.+) ate too much glass",
        "suicide1":" (.+) killed .+",
        "suicide2":" (.+) is done with the world",
        "fall_kill1":" (.+) hit the gruond hard, real hard",
        "fall_kill2":" (.+) plummets to .+ death",
        "crush_kill":" (.+) was flattened",
      	"drown_kill":" (.+) sank like a rock",
        "slime_kill":" (.+) melted",
        "lava_kill":" (.+) does a back flip into the lava",
        "explosive_kill":" (.+) blew up",
        "laser_kill":" (.+) saw the light",
        "blaster_kill":" (.+) got blasted",
        "trigger_hurt_kill":" (.+) was in the wrong place",
        "grenade_kill":" (.+) didn't see (.+)'s handgrenade",
        "grenade_held_kill":" (.+) tried to put the pin back in",
        "grenade_splash_suicide":" (.+) didn't throw .+ grenade far enough",
        "grenade_splash_suicide2":" (.+) tripped on .+ own grenade",
        "grenade_splash_suicide3":" (.+) blew .+ up",
        "fly_kill":" (.+) was taught how to fly by (.+)",
       	"bleed_death":" (.+) bleeds to death"
}


other_msgs = {  "round_over":"] The round is over:",
		"join":"] (.+) entered the game", # not useful
		"quit":"] (.+) disconnected",
		"namechange":"] (.+) is now known as (.+)."}
